FROM mcr.microsoft.com/dotnet/aspnet:10.0@sha256:1aacc8154bc3071349907dae26849df301188be1a2e1f4560b903fb6275e481a AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:25d14b400b75fa4e89d5bd4487a92a604a4e409ab65becb91821e7dc4ac7f81f AS build
WORKDIR /src

COPY ["./Database/DatabaseMigrator/DatabaseMigrator.csproj", "DatabaseMigrator.csproj"]
COPY ["Directory.Packages.props", "Directory.Packages.props"]
COPY ["Directory.Build.targets", "Directory.Build.targets"]
COPY ["Directory.Build.props", "Directory.Build.props"]
COPY ["stylecop.json", "stylecop.json"]
COPY [".editorconfig", ".editorconfig"]

RUN dotnet restore "DatabaseMigrator.csproj"

COPY ./Database/ .

WORKDIR "/src"
RUN dotnet build "DatabaseMigrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DatabaseMigrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ADD ./Database/entrypoint_DatabaseMigrator.sh /
ADD ./Database/CompanyName.MyMeetings.Database/Scripts/Migrations /migrations/

# Copy wait-for-it.sh into our image
COPY ./Database/wait-for-it.sh wait-for-it.sh
# Make it executable, in Linux
RUN chmod +x wait-for-it.sh

#ENTRYPOINT ["/bin/bash", "/entrypoint_DatabaseMigrator.sh"]
