FROM mcr.microsoft.com/dotnet/aspnet:10.0@sha256:c433886fdfe33c6427966a412328867b2be9a64f540a105d08943c2dc6fba39b AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:127d7d4d601ae26b8e04c54efb37e9ce8766931bded0ee59fcd799afd21d6850 AS build
WORKDIR /src

COPY ["./Database/DatabaseMigrator/DatabaseMigrator.csproj", "DatabaseMigrator.csproj"]
COPY ["Directory.Packages.props", "Directory.Packages.props"]
COPY ["Directory.Build.targets", "Directory.Build.targets"]
COPY ["Directory.Build.props", "Directory.Build.props"]
COPY ["stylecop.json", "stylecop.json"]
COPY [".editorconfig", ".editorconfig"]

RUN dotnet restore "DatabaseMigrator.csproj"

COPY ./Database/ .

WORKDIR "/src"
RUN dotnet build "DatabaseMigrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DatabaseMigrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ADD ./Database/entrypoint_DatabaseMigrator.sh /
ADD ./Database/CompanyName.MyMeetings.Database/Scripts/Migrations /migrations/

# Copy wait-for-it.sh into our image
COPY ./Database/wait-for-it.sh wait-for-it.sh
# Make it executable, in Linux
RUN chmod +x wait-for-it.sh

#ENTRYPOINT ["/bin/bash", "/entrypoint_DatabaseMigrator.sh"]
